improve error handling
- force oneline response body (in case of html in response)
- don't crash when printing exception error
  > During handling of the above exception, another exception occurred:
  > AttributeError: 'NoneType' object has no attribute 'status_code'
- use tqdm.write instead of print to avoid interfering with tqdm progressbar

Signed-off-by: HARPER Jon <jon.harper87@gmail.com>